apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cluster-configurator
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services", "configmaps"]
    verbs: ["create", "delete", "get", "list", "update", "watch"]
