apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: viewer
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "nodes"]
    verbs: ["get", "list", "watch"]
